    # Generated by Django 5.1.2 on 2024-10-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temporadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomTemp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomIng', models.CharField(max_length=100)),
                ('TempId_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.temporadas')),
            ],
        ),
    ]
