# Generated by Django 5.1.2 on 2024-10-31 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_categorias_dificultades_alter_ingredientes_noming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomRec', models.CharField(max_length=40)),
                ('ElRec', models.CharField(max_length=600)),
                ('TREc', models.CharField(max_length=15)),
                ('CatId_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.categorias')),
                ('DifId_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.dificultades')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientesRecetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PesoIng', models.IntegerField(default=0)),
                ('IngId_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.ingredientes')),
                ('RecId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.recetas')),
            ],
        ),
    ]
