# Generated by Django 5.1.2 on 2024-11-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NumF", models.IntegerField(max_length=15)),
                ("Cliente", models.CharField(max_length=300)),
                ("FechaF", models.DateField()),
                ("Mail", models.EmailField(max_length=254)),
                ("Dirc", models.CharField(max_length=300)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PAGADA", "Pagada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("FechaC", models.DateField(auto_now_add=True)),
                ("FechaM", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DetalleFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NomP", models.CharField(max_length=300)),
                ("Precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Tipo", models.CharField(max_length=100)),
                ("PrecioIVA", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "NumF",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="visuafact.factura",
                    ),
                ),
            ],
        ),
    ]
