# Generated by Django 5.1.2 on 2024-11-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuafact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="NumF",
            field=models.IntegerField(),
        ),
    ]
