# Generated by Django 5.1.2 on 2024-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visuafact", "0002_alter_factura_numf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="FechaC",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="factura",
            name="FechaM",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
