# Generated by Django 4.1 on 2024-11-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facturas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NumF", models.IntegerField()),
                ("NomProv", models.CharField(max_length=300)),
                ("FechaF", models.DateField()),
                ("DireP", models.CharField(max_length=300)),
                ("CCoste", models.CharField(max_length=20)),
                ("Mail", models.EmailField(max_length=254)),
                ("FechaE", models.DateTimeField(auto_now_add=True)),
                ("FechaM", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Detalles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NomP", models.CharField(max_length=300)),
                ("Precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "NumF",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factvisual.facturas",
                    ),
                ),
            ],
        ),
    ]
