# Generated by Django 4.1 on 2024-11-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("factvisual", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalles",
            name="NumF",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="factvisual.facturas",
            ),
        ),
    ]
