# Generated by Django 4.1 on 2024-11-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factvisual", "0002_alter_detalles_numf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalles",
            name="NomP",
            field=models.CharField(max_length=300, verbose_name="Nombre del producto"),
        ),
        migrations.AlterField(
            model_name="facturas",
            name="CCoste",
            field=models.CharField(
                choices=[
                    ("COMERCIAL", "Comercial"),
                    ("FABRICA 1", "Fabrica 1"),
                    ("ALMACEN 2", "Almacen 2"),
                ],
                default="COMERCIAL",
                max_length=20,
                verbose_name="Centro de coste",
            ),
        ),
        migrations.AlterField(
            model_name="facturas",
            name="DireP",
            field=models.CharField(
                max_length=300, verbose_name="Dirección del proveedor"
            ),
        ),
        migrations.AlterField(
            model_name="facturas",
            name="FechaF",
            field=models.DateField(verbose_name="Fecha de la factura"),
        ),
        migrations.AlterField(
            model_name="facturas",
            name="Mail",
            field=models.EmailField(max_length=254, verbose_name="Email del proveedor"),
        ),
        migrations.AlterField(
            model_name="facturas",
            name="NomProv",
            field=models.CharField(max_length=300, verbose_name="Nombre del proveedor"),
        ),
        migrations.AlterField(
            model_name="facturas",
            name="NumF",
            field=models.IntegerField(verbose_name="Número de factura"),
        ),
    ]
